version: 1.0.0.{build}
before_build:
- cmd: nuget restore
build:
  project: lets-code-ci-session-2.sln
  verbosity: minimal
test_script:
- .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"C:\projects\lets-code-ci-session-2\lets-code-ci-session-2.Tests\bin\Debug\lets-code-ci-session-2.Tests.dll -noshadow -appveyor" -returntargetcode -filter:"+[lets_code_ci_session_2]* -[lets_code_ci_session_2.Tests]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:.\coverage.xml
- "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
- pip install codecov
- codecov -f "coverage.xml"